import { NextResponse } from 'next/server'
import { createSupabaseServer } from '../../../../lib/auth'

export async function POST(request:Request){
 const s=await createSupabaseServer();const {data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await request.json();if(!b.taskId)return NextResponse.json({error:'taskId is required'},{status:400});
 const {data:task}=await s.from('tasks').select('id,title,description,project_id,github_branch,github_pr_number').eq('id',b.taskId).single();if(!task)return NextResponse.json({error:'Task not found'},{status:404});if(task.github_pr_number)return NextResponse.json({error:'Pull request already linked',number:task.github_pr_number},{status:409});
 const {data:p}=await s.from('projects').select('github_owner,github_repo,github_default_branch').eq('id',task.project_id).single();if(!p?.github_owner||!p.github_repo||!task.github_branch)return NextResponse.json({error:'Task branch and project GitHub repository are required'},{status:400});const token=process.env.GITHUB_TOKEN;if(!token)return NextResponse.json({error:'GitHub integration is not configured'},{status:503});
 const r=await fetch(`https://api.github.com/repos/${p.github_owner}/${p.github_repo}/pulls`,{method:'POST',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({title:b.title||task.title,head:task.github_branch,base:p.github_default_branch||'main',body:b.body||task.description||`VibeBase task: ${task.title}`,draft:Boolean(b.draft)})});if(!r.ok)return NextResponse.json({error:`GitHub PR creation failed (${r.status})`},{status:502});const pr=await r.json();await s.from('tasks').update({github_pr_number:pr.number,github_pr_url:pr.html_url,status:'review',workflow_status:'review'}).eq('id',task.id);return NextResponse.json({number:pr.number,url:pr.html_url,branch:task.github_branch})
}
