'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function ProjectDetail({ params }: { params: Promise<{ id: string }> }) {
 const [id,setId]=useState(''); const [project,setProject]=useState<any>(null); const [features,setFeatures]=useState<any[]>([]); const [name,setName]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{params.then(p=>setId(p.id))},[params]); useEffect(()=>{if(!id)return; fetch('/api/projects').then(r=>r.json()).then(j=>setProject((j.projects||[]).find((p:any)=>p.id===id))); fetch('/api/features?projectId='+id).then(r=>r.json()).then(j=>setFeatures(j.features||[]))},[id])
 async function addFeature(){if(!name.trim())return;setBusy(true);setError('');const r=await fetch('/api/features',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:id,name,priority:'medium'})});const j=await r.json();if(r.ok){setFeatures(x=>[...x,j.feature]);setName('')}else setError(j.error||'Unable to create feature');setBusy(false)}
 async function removeFeature(fid:string){await fetch('/api/features?id='+fid,{method:'DELETE'});setFeatures(x=>x.filter(f=>f.id!==fid))}
 if(!project&&id)return <main className="p-10 text-zinc-500">Loading project…</main>
 return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-6xl"><Link href="/projects" className="text-sm text-zinc-500">← Projects</Link><header className="mt-6 rounded-3xl border border-zinc-800 bg-zinc-950 p-7"><p className="text-xs tracking-[.2em] text-zinc-500">PROJECT</p><h1 className="mt-2 text-3xl font-bold">{project?.name}</h1><p className="mt-3 max-w-3xl text-zinc-400">{project?.description||'No description yet.'}</p><div className="mt-6 grid gap-4 md:grid-cols-3"><Info title="Problem" value={project?.problem}/><Info title="Audience" value={project?.target_audience}/><Info title="Vision" value={project?.vision}/></div></header><section className="mt-6 rounded-3xl border border-zinc-800 bg-zinc-950 p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Features</h2><p className="mt-1 text-sm text-zinc-500">Prioritize the product scope for this project.</p></div><div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addFeature()} placeholder="New feature…" className="rounded-xl border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm outline-none"/><button disabled={busy} onClick={addFeature} className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-black">Add</button></div></div>{error&&<p className="mt-4 text-sm text-red-400">{error}</p>}<div className="mt-6 space-y-2">{features.length===0?<p className="rounded-xl border border-dashed border-zinc-800 p-6 text-sm text-zinc-600">No features yet.</p>:features.map(f=><div key={f.id} className="flex items-center justify-between rounded-xl border border-zinc-800 p-4"><div><p className="font-medium">{f.name}</p><p className="mt-1 text-xs text-zinc-500">{f.priority}</p></div><button onClick={()=>removeFeature(f.id)} className="text-xs text-zinc-500 hover:text-white">Delete</button></div>)}</div></section></div></main>
}
function Info({title,value}:{title:string,value?:string}){return <div className="rounded-2xl border border-zinc-800 p-4"><p className="text-xs uppercase tracking-wider text-zinc-600">{title}</p><p className="mt-2 text-sm text-zinc-300">{value||'Not defined'}</p></div>}
