'use client'

import { useState } from 'react'

export default function AIPage() {
  const [context,setContext]=useState(''); const [request,setRequest]=useState(''); const [prompt,setPrompt]=useState(''); const [answer,setAnswer]=useState(''); const [loading,setLoading]=useState(false)
  async function generate(){setLoading(true);const r=await fetch('/api/ai/prompt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({context,request})});const j=await r.json();setPrompt(j.prompt||j.error||'');setLoading(false)}
  async function ask(){setLoading(true);const r=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:'You are the VibeBase project assistant. Be precise and implementation-oriented.'},{role:'user',content:request+'\n\nProject context:\n'+context}]})});const j=await r.json();setAnswer(j.message||j.error||'');setLoading(false)}
  return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-6xl"><header className="mb-8"><p className="text-sm tracking-[.2em] text-zinc-500">VIBEBASE / AI ASSISTANT</p><h1 className="mt-2 text-3xl font-bold">Build with project context</h1><p className="mt-2 text-zinc-400">Generate a deterministic coding prompt or ask the configured AI provider.</p></header><div className="grid gap-5 lg:grid-cols-2"><label className="text-sm">Project context<textarea value={context} onChange={e=>setContext(e.target.value)} className="mt-2 h-72 w-full rounded-2xl border border-zinc-800 bg-zinc-950 p-4" placeholder="Paste or load project context…"/></label><label className="text-sm">Request<textarea value={request} onChange={e=>setRequest(e.target.value)} className="mt-2 h-72 w-full rounded-2xl border border-zinc-800 bg-zinc-950 p-4" placeholder="What should the AI implement?"/></label></div><div className="mt-5 flex gap-3"><button onClick={generate} disabled={loading} className="rounded-xl bg-white px-5 py-3 text-sm font-medium text-black">Generate prompt</button><button onClick={ask} disabled={loading} className="rounded-xl border border-zinc-700 px-5 py-3 text-sm">Ask AI</button></div>{prompt&&<section className="mt-6"><h2 className="font-semibold">Generated prompt</h2><pre className="mt-3 overflow-auto whitespace-pre-wrap rounded-2xl border border-zinc-800 bg-zinc-950 p-5 text-sm text-zinc-300">{prompt}</pre></section>}{answer&&<section className="mt-6"><h2 className="font-semibold">AI response</h2><div className="mt-3 whitespace-pre-wrap rounded-2xl border border-zinc-800 bg-zinc-950 p-5 text-sm text-zinc-300">{answer}</div></section>}</div></main>
}
