'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'

export default function NewProjectPage() {
  const router = useRouter(); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
  const [form,setForm]=useState({name:'',description:'',problem:'',targetAudience:'',vision:'',techStack:''})
  function set(key:string,value:string){setForm({...form,[key]:value})}
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');const r=await fetch('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,techStack:form.techStack.split(',').map(x=>x.trim()).filter(Boolean)})});const j=await r.json();if(!r.ok){setError(j.error||'Could not create project');setLoading(false);return}router.push('/projects');router.refresh()}
  return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-3xl"><header className="mb-8"><p className="text-sm tracking-[.2em] text-zinc-500">VIBEBASE / NEW PROJECT</p><h1 className="mt-2 text-3xl font-bold">Define your idea</h1><p className="mt-2 text-zinc-400">Capture enough context for humans and AI to build from the same source of truth.</p></header><form onSubmit={submit} className="space-y-5 rounded-3xl border border-zinc-800 bg-zinc-950 p-6"><Field label="Project name" value={form.name} onChange={v=>set('name',v)} required placeholder="e.g. VibeBase"/><Field label="Description" value={form.description} onChange={v=>set('description',v)} placeholder="What are you building?"/><Field label="Problem" value={form.problem} onChange={v=>set('problem',v)} placeholder="Which problem does it solve?"/><Field label="Target audience" value={form.targetAudience} onChange={v=>set('targetAudience',v)} placeholder="Who is it for?"/><Field label="Vision" value={form.vision} onChange={v=>set('vision',v)} placeholder="What should the product become?"/><Field label="Tech stack" value={form.techStack} onChange={v=>set('techStack',v)} placeholder="Next.js, Supabase, Vercel"/><div className="flex items-center gap-4 pt-2"><button disabled={loading} className="rounded-xl bg-white px-5 py-3 font-medium text-black disabled:opacity-50">{loading?'Creating…':'Create project'}</button>{error&&<p className="text-sm text-red-400">{error}</p>}</div></form></div></main>
}
function Field({label,value,onChange,placeholder,required=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;required?:boolean}){return <label className="block text-sm font-medium">{label}<input required={required} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-zinc-100 outline-none placeholder:text-zinc-600 focus:border-zinc-600"/></label>}
